### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by bloodcurdle** [TimBroddin/cryptocoincount#10]
Hello, can anyone tell me how to install it? 
I'm having tough time installing it on my server

**Comment by TimBroddin** [comment]
What's the problem?

**Comment by bloodcurdle** [comment]
Actually i'm not able to set it up on my server. Can you provide me a detail guide on how to do so, i would be grateful

**Comment by TimBroddin** [comment]
Make sure you have MongoDB installed, or have an instance running somewhere.

Set your connection string in an environment variable

`export MONGODB_URI="mongodb://connection_string"`

Run the worker script (populates the db): 
`yarn run worker`

Alter the config file  `src/config.js` (change api base to your server)

Build the app:
`yarn run build`

Run the app:
`yarn start`

But why would you want to do this if you can just use cryptocoincount.com? :)
