### ISSUE TITLE
Feedback when trying to import a code

### ISSUE THREAD

**Issue by eimfach** [TimBroddin/cryptocoincount#2]
I tried to import the code and it didn't work.. Also there was no message/feedback at all which felt like a little bad experience for me..

is there a reason why you only do a ```console.log``` in ```ImportForm.importCode``` (instead of e.g. ```message.error```) ?

Also I wanted to leave some positive feedback here, nice application so far. I will use it (and I am also put for contribution)

**Comment by TimBroddin** [comment]
I'll replace the import/export code with something new soon. The QR-code doesn't really scale when you have 50+ coins, and browser support is lacking.

**Comment by TimBroddin** [comment]
Thanks for the positive feedback!

**Comment by Raylehnhoff** [comment]
Something worth considering - you could run the json blob through a lzw compression to make the string smaller. 

When you read it, attempt to decompress and try to json.parse it - if it fails its not valid.

I do this on playoffpredictors.com to serialize the results of a nfl season, though that's using some magic to not encode the json directly. 

Just some food for thought.

**Comment by TimBroddin** [comment]
Thanks! I'm already using LZ-compression, but I think it's not enough for really big portfolio.

I think I'm going to use a system where the data is temporarely saved on the server, and you have to copy a 6-digit code.

**Comment by TimBroddin** [comment]
Implemented the new system, closing this issue
