### ISSUE TITLE
Since the last update, the price doesn't update

### ISSUE THREAD

**Issue by Raylehnhoff** [TimBroddin/cryptocoincount#3]
My price has been stuck on the same amount all day. It seems like it's not updating the price anymore, even with hard refreshes

**Comment by TimBroddin** [comment]
I noticed this too. Will look into it today!

**Comment by TimBroddin** [comment]
Appcache was doing wonky again, removed it and it should work again (refresh until you get 1.3.2 at the bottom).

I'm leaving Appcache out for now.

**Comment by Raylehnhoff** [comment]
I'm seeing 1.3.2 as the version, but still seeing the same total crypto
worth. I got the prompt to update - are you sure this is resolved?

**Comment by TimBroddin** [comment]
What browser/OS are you using?

**Comment by Raylehnhoff** [comment]
Chrome on an android 6p. 

Desktop - windows 10, chrome latest, same issue. 

Other browsers don't have the older cache but I'll try to reproduce it there as well.

**Comment by Raylehnhoff** [comment]
I was able to reproduce this on "free ad block browser" from the play store, so this isn't just a chrome issue. That browser had never been to this site before either. 

I see the arrows change but the total crypto worth never updates. I don't this this issue is resolved.

**Comment by TimBroddin** [comment]
I'm looking into it :)

**Comment by TimBroddin** [comment]
Could you check again? Deployed v1.3.3

**Comment by Raylehnhoff** [comment]
It seems corrected now. Good work!
