### ISSUE TITLE
Add BTC/common coins to drop-down of currencies to represent portfolio

### ISSUE THREAD

**Issue by KaiserTom** [TimBroddin/cryptocoincount#6]
BTC is the defacto "index" that many other coins are compared and rise and fall to. Having it as an option to display my portfolio in BTC allows me to gauge how well my investments have done versus that "index".

**Comment by TimBroddin** [comment]
I added it, deploying right now!

**Comment by KaiserTom** [comment]
Amazing, thank you very much!
